### ISSUE TITLE
Remove the clear button from the picker

### ISSUE THREAD

**Issue by Domuska** [alexiscolin/vue-timeselector#3]
Is it possible to anyhow just completely remove the clear time button from the row displaying the time user has selected?

Thanks!

**Comment by alexiscolin** [comment]
Actually, you can remove the button by using a `display: none` on the clear button class `.vtimeselector__clear`. I will add a note on the readme ile about that class. Does it help you ?

**Comment by Domuska** [comment]
That's exactly what I was searching for. Thank you. :)
