### ISSUE TITLE
Display AM PM in timeselector

### ISSUE THREAD

**Issue by dugjohnson** [alexiscolin/vue-timeselector#4]
I have everything set for the dropdown using 12 hours and am/pm, but I can't see where to format the display to show am/pm.

I don't see how to display the difference between 2:03 A and 2:03 P

Am I missing it, or is it not there?

If not there, I will try to figure it out and do a pull request.

Unless you don't want it there for some reason

**Comment by lucascorrea97** [comment]
I'm missing it too! It'd be a nice feature

**Comment by alexiscolin** [comment]
Hey guys, I'm sorry for the delay (I wasn't coding since a ling time). Tell me if I understand right or not, but what you want is a way to display in  the AM-PM code inside the input generated by the component ? 
That's a good idea ! I will implement that feature very soon.

**Comment by alexiscolin** [comment]
I just published a way to do that with a new formatter : `a`. By default, if you don't want formatting the display value, the component will add the AM/PM code in 12h mode.

It will display `AM` or `PM` according to the hour.
