### ISSUE TITLE
Unable to pre-fill the modal with a fetched date string

### ISSUE THREAD

**Issue by eakenbor** [alexiscolin/vue-timeselector#7]
Please I am unable to pre-fill the modal with a date string on loading the component. Only null and new Date() default works. Any other time does not work as it throws the error: "TypeError: this.value.getHours is not a function"

Here is my code
<timeselector
                  :value="'Sat Jun 29 2019 00:00:00 GMT+0200 (Central European Summer Time)'"
                  :disabled="monday.isNotWorking"
                  :placeholder="'Start'"
                  :displayFormat="'HH mm'"
                  :interval="{h:1, m:30}"
                  returnFormat="HH.mm MON START"
                  @formatedTime="formatedTime"
                  @cleared="myClearedFunc('monday', 'start')"
                ></timeselector>

Also, the placeholder does not disappear when there is an initial default value binded.

Please can someone tell me what I am doing wrong? Thanks.

**Comment by alexiscolin** [comment]
Hey eakenbor,

Have you tried to convert your string date into a real Date object ? As for today, `value`props must be a null or Date object. Maybe creating a DATE <-> STRING converter or another type of props (as day, hour, min, sec... props) in the component could be a good idea.

Regarding to the placeholder. You are right, it acts like a real input placeholder. If you have already set a `value` inside the components, the value replaces the placeholder. 
If I understand well, you would like to set an initial value for the dropdown menu (on click), but not directly inside the input box ? The placeholder would disappear after the first click on the dropdown menu ?

**Comment by eakenbor** [comment]
Thanks alexiscolin. It worked when I passed the date string into a new Date() object. For the placeholder, it also works fine now.

Also see if you can improve the UI experience in the future by ensuring the time drop down menu disappears after clicking on the time instead of having to click anywhere outside the menu for it to disappear.

Second, for the returnFormat prop, when additional strings are attached to the standard time formats, say for instance "monday", it emits "m" as the first digit of the minute and the let "a" as AM. That is as"1ondAMy" To avoid this, I would have to use all upper casing "MONDAY". However, the problem persists for example "THURSDAY". "H" will add hour to the emitted string to become for example "T3URSDAY. To avoid that I would have to misspell as "TURSDAY" or something else. See if you can fix this or maybe consider passing arguments through @formatedTime="formatedTime" for it to be easy to identify the specific selector when there are several timeselector modals.

**Comment by alexiscolin** [comment]
That's an interesting idea, but the dropdow menu need to be closed only after the user has selected every time operator he desire (h, m, s...). So we need a way to know when the user has finished to set the complete time to do that. 
On the second issue you encounter, there are already a way to avoid that weird behaviour. You can escape those "reserved time operators" (letter) by using brackets :

> It's possible to escape a letter used for formatting ("h", "H", "m" ...) by surrounding it with brackets, eg. HH[h]mm could render 01h35. Time may be set to UTC or not in order to display and return UTC time.

Feel free to share all your ideas. Thank you for you feedback !
