### ISSUE TITLE
Items miss selected class when padTime is set as true

### ISSUE THREAD

**Issue by netodomenico** [alexiscolin/vue-timeselector#8]
Hi, after trying in every way to come up with this problem I discovered that setting the attribute padTime to false the bug disappears, and so I think we can take it for granted that that attribute conflicts with something else. Can you give me support in this regard?

**Comment by alexiscolin** [comment]
Thank you for your feedback and your inputs, I'm going to check that behavior soon.

**Comment by netodomenico** [comment]
#9 Fixed here
